### PR TITLE
allow non-gzip layers

### PR DESCRIPTION
**Pull request by tofay**
I'm exploring using zstd layers in rpmoci: to do that I'd like to create a `Layer` with a different media type and then use `OciDir::push_layer`

### CODE REVIEW

**Comment by ariel-miculas** [comment]
I'm wondering whether we should use a Descriptor instead of a Blob and MediaType in the Layer struct.

**Comment by tofay** [comment]
> I'm wondering whether we should use a Descriptor instead of a Blob and MediaType in the Layer struct.

Makes sense. I'm also wondering why the Layer fields are public at all.

**Comment by cgwalters** [comment]
> Makes sense. I'm also wondering why the Layer fields are public at all.

Versus having getters? I'm in favor, though let's just start a list of things to change in the next server bump...I don't have a big appetite for another semver just for that.

**Review by cgwalters — APPROVED** [review]
Ah yeah what we had before was clearly suboptimal.

Hmm maybe for consistency it's `GzipLayerWriter` that sets the mime type explicitly too? I guess yeah that gets to wanting to have an explicit descriptor. 

Short of some server-breaking changes this looks sane to me.

**Comment by tofay** [comment]
> Short of some server-breaking changes this looks sane to me.

This change is semver breaking (https://doc.rust-lang.org/cargo/reference/semver.html#struct-add-public-field-when-no-private).

**Comment by cgwalters** [comment]
> This change is semver breaking (https://doc.rust-lang.org/cargo/reference/semver.html#struct-add-public-field-when-no-private).

Technically...yes, but IMO practically no one is using struct literals for this.

Anyways I am also OK to just bump server and make other changes too, though we should also I think try to "settle down" after hopefully just one more bump for a while hopefully.

**Comment by ariel-miculas** [comment]
I do have some stuff lined up besides #22, basically to implement [this function](https://github.com/project-machine/puzzlefs/blob/master/puzzlefs-lib/src/oci.rs#L213) in ocidir-rs

**Pull request merged**
